{
  "name": "durandal/amd/almond-custom",
  "inlineText": true,
  "stubModules": [
    "durandal/amd/text"
  ],
  "paths": {
    "text": "durandal/amd/text"
  },
  "baseUrl": "C:\\Users\\max.nunes\\Documents\\Visual Studio 2012\\Projects\\Perfin\\Perfin\\Perfin.UI.Web\\App",
  "mainConfigFile": "C:\\Users\\max.nunes\\Documents\\Visual Studio 2012\\Projects\\Perfin\\Perfin\\Perfin.UI.Web\\App\\main.js",
  "include": [
    "main-built",
    "main",
    "charts/chart.totalCategoriesByMonth",
    "charts/chart.totalTypeTransactionsByMonth",
    "common/assets",
    "common/breadcrumb",
    "common/config",
    "common/config.route",
    "common/logger",
    "common/utils",
    "durandal/app",
    "durandal/composition",
    "durandal/events",
    "durandal/http",
    "text!durandal/messageBox.html",
    "durandal/messageBox",
    "durandal/modalDialog",
    "durandal/system",
    "durandal/viewEngine",
    "durandal/viewLocator",
    "durandal/viewModel",
    "durandal/viewModelBinder",
    "durandal/widget",
    "durandal/plugins/router",
    "durandal/transitions/entrance",
    "models/model.category",
    "models/model.entry",
    "models/model",
    "models/model.mapper",
    "models/model.typeTransaction",
    "models/model.user",
    "repositories/datacontext",
    "repositories/dataprimer",
    "repositories/entry",
    "repositories/repository.assets",
    "repositories/repository.category",
    "repositories/repository.entry",
    "repositories/repository",
    "repositories/repository.user",
    "security/authentication",
    "security/authentication.provider.auth0",
    "services/callback.dataservice",
    "services/dataservice.assets",
    "services/dataservice.category",
    "services/dataservice.entry",
    "services/dataservice",
    "services/dataservice.user",
    "viewmodels/public",
    "viewmodels/shell",
    "viewmodels/welcome",
    "viewmodels/category/add",
    "viewmodels/category/details",
    "viewmodels/category/show",
    "viewmodels/Entry/add",
    "viewmodels/Entry/daily",
    "viewmodels/Entry/details",
    "viewmodels/Entry/show",
    "viewmodels/user/add",
    "viewmodels/user/details",
    "viewmodels/user/login",
    "viewmodels/user/register",
    "viewmodels/user/show",
    "text!views/detail.html",
    "text!views/nav-side.html",
    "text!views/nav-top.html",
    "text!views/public.html",
    "text!views/shell.html",
    "text!views/welcome.html",
    "text!views/category/add.html",
    "text!views/category/details.html",
    "text!views/category/show.html",
    "text!views/Entry/add.html",
    "text!views/Entry/daily.html",
    "text!views/Entry/details.html",
    "text!views/Entry/show.html",
    "text!views/user/add.html",
    "text!views/user/details.html",
    "text!views/user/login.html",
    "text!views/user/register.html",
    "text!views/user/show.html",
    "text!views/_shared/breadcrumb.html"
  ],
  "exclude": [],
  "keepBuildDir": true,
  "optimize": "uglify2",
  "out": "C:\\Users\\max.nunes\\Documents\\Visual Studio 2012\\Projects\\Perfin\\Perfin\\Perfin.UI.Web\\App\\main-built.js",
  "pragmas": {
    "build": true
  },
  "wrap": true,
  "insertRequire": [
    "main"
  ]
}